FROM node:22-alpine

RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.json ./pnpm-lock.json

COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY ./apps/web ./apps/web

RUN pnpm i

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "star:web"]