FROM node:22-alpine

RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.json ./pnpm-lock.json

COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY ./apps/https-server ./apps/https-server

RUN pnpm i

RUN pnpm run build

EXPOSE 3002

CMD ["pnpm", "run", "start:http-server"]